### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by comerc**

### CODE REVIEW

**Comment by rhyslbw** [comment]
Thanks for the correction @comerc , however all changes must be requested against _develop_ as we use git-flow. Will close this one

**Comment by comerc** [comment]
Really? :)

**Comment by DominikGuzei** [comment]
@rhyslbw in such simple cases i think we can still just accept the change to master 😉

**Comment by rhyslbw** [comment]
Might seem like a trivial issue, particularly early on in a project where the released version (master) is close to develop, but now develop is out of sync and needs to be back merged to get this update.

**Comment by DominikGuzei** [comment]
Yeah, of course this is depending on the case, but here it was no problem at all … and for readme updates only fixing a single link i would always do it like that, this is basically a hotfix.

**Pull request merged**
